import numpy as np


values_per_joint = 3
values_per_foot = 2

# Quadruped joints
QUADRUPED_FRONT_LEFT_HIP = np.arange(0, values_per_joint)
QUADRUPED_FRONT_LEFT_THIGH = np.arange(QUADRUPED_FRONT_LEFT_HIP[-1] + 1, QUADRUPED_FRONT_LEFT_HIP[-1] + 1 + values_per_joint)
QUADRUPED_FRONT_LEFT_CALF = np.arange(QUADRUPED_FRONT_LEFT_THIGH[-1] + 1, QUADRUPED_FRONT_LEFT_THIGH[-1] + 1 + values_per_joint)
QUADRUPED_FRONT_RIGHT_HIP = np.arange(QUADRUPED_FRONT_LEFT_CALF[-1] + 1, QUADRUPED_FRONT_LEFT_CALF[-1] + 1 + values_per_joint)
QUADRUPED_FRONT_RIGHT_THIGH = np.arange(QUADRUPED_FRONT_RIGHT_HIP[-1] + 1, QUADRUPED_FRONT_RIGHT_HIP[-1] + 1 + values_per_joint)
QUADRUPED_FRONT_RIGHT_CALF = np.arange(QUADRUPED_FRONT_RIGHT_THIGH[-1] + 1, QUADRUPED_FRONT_RIGHT_THIGH[-1] + 1 + values_per_joint)
QUADRUPED_BACK_LEFT_HIP = np.arange(QUADRUPED_FRONT_RIGHT_CALF[-1] + 1, QUADRUPED_FRONT_RIGHT_CALF[-1] + 1 + values_per_joint)
QUADRUPED_BACK_LEFT_THIGH = np.arange(QUADRUPED_BACK_LEFT_HIP[-1] + 1, QUADRUPED_BACK_LEFT_HIP[-1] + 1 + values_per_joint)
QUADRUPED_BACK_LEFT_CALF = np.arange(QUADRUPED_BACK_LEFT_THIGH[-1] + 1, QUADRUPED_BACK_LEFT_THIGH[-1] + 1 + values_per_joint)
QUADRUPED_BACK_RIGHT_HIP = np.arange(QUADRUPED_BACK_LEFT_CALF[-1] + 1, QUADRUPED_BACK_LEFT_CALF[-1] + 1 + values_per_joint)
QUADRUPED_BACK_RIGHT_THIGH = np.arange(QUADRUPED_BACK_RIGHT_HIP[-1] + 1, QUADRUPED_BACK_RIGHT_HIP[-1] + 1 + values_per_joint)
QUADRUPED_BACK_RIGHT_CALF = np.arange(QUADRUPED_BACK_RIGHT_THIGH[-1] + 1, QUADRUPED_BACK_RIGHT_THIGH[-1] + 1 + values_per_joint)
# Quadruped feet
QUADRUPED_FRONT_LEFT_FOOT = np.arange(QUADRUPED_BACK_RIGHT_CALF[-1] + 1, QUADRUPED_BACK_RIGHT_CALF[-1] + 1 + values_per_foot)
QUADRUPED_FRONT_RIGHT_FOOT = np.arange(QUADRUPED_FRONT_LEFT_FOOT[-1] + 1, QUADRUPED_FRONT_LEFT_FOOT[-1] + 1 + values_per_foot)
QUADRUPED_BACK_LEFT_FOOT = np.arange(QUADRUPED_FRONT_RIGHT_FOOT[-1] + 1, QUADRUPED_FRONT_RIGHT_FOOT[-1] + 1 + values_per_foot)
QUADRUPED_BACK_RIGHT_FOOT = np.arange(QUADRUPED_BACK_LEFT_FOOT[-1] + 1, QUADRUPED_BACK_LEFT_FOOT[-1] + 1 + values_per_foot)
# General
TRUNK_LINEAR_VELOCITIES = np.arange(QUADRUPED_BACK_RIGHT_FOOT[-1] + 1, QUADRUPED_BACK_RIGHT_FOOT[-1] + 1 + 3)
TRUNK_ANGULAR_VELOCITIES = np.arange(TRUNK_LINEAR_VELOCITIES[-1] + 1, TRUNK_LINEAR_VELOCITIES[-1] + 1 + 3)
GOAL_VELOCITIES = np.arange(TRUNK_ANGULAR_VELOCITIES[-1] + 1, TRUNK_ANGULAR_VELOCITIES[-1] + 1 + 3)
PROJECTED_GRAVITY = np.arange(GOAL_VELOCITIES[-1] + 1, GOAL_VELOCITIES[-1] + 1 + 3)
HEIGHT = np.arange(PROJECTED_GRAVITY[-1] + 1, PROJECTED_GRAVITY[-1] + 1 + 1)

# Total observation size
OBSERVATION_SIZE = HEIGHT[-1] + 1


def update_nr_height_samples(nr_height_samples):
    global HEIGHT
    HEIGHT = np.arange(PROJECTED_GRAVITY[-1] + 1, PROJECTED_GRAVITY[-1] + 1 + nr_height_samples)
    global OBSERVATION_SIZE
    OBSERVATION_SIZE = HEIGHT[-1] + 1
